### ISSUE TITLE
Clean up/make usable from the outside?

### ISSUE THREAD

**Issue by Frotty** [Retera/JWC3#1]
Hi, there is some interesting stuff in here.
Sadly, the repo seems to be in a terrible state. It contains tons of Binaries, logfiles, strange copies and other things that shouldn't be in here. The only projects using a build/dep tool seem to be the "RealityInteractive*" ones.

Also the inter-dependencies seem screwed up abit if the matrix eater depends on the WorldEdit module, making it difficult to copy parts of the code.

Moving all non-JWC3/matrix eater related resources into separate repos could be a start.

Will you ever clean this up and use some proper dependency & build management, e.g. gradle?

**Comment by Retera** [comment]
Those are some good ideas. At the moment I'm less focused on dependency management and more focused on program functionality of the matrix eater software itself. I'm trying to do some additions and stuff of features and upgrades that I've wanted to make for a long time.
I've used gradle before, but usually just by copying the build scripts because they're annoying syntactically. Most of that stuff isn't very important when I'm working solo and can just push export to JAR in the IDE.

But, right now, that master branch is in a super messed up state. Lots of compile errors. I've been working on some major refactoring, and probably won't be done for another couple of months.
Are you saying you want to build it? If you watch the [developer setup video](https://www.youtube.com/watch?v=XIy-jhXmZ4E), you can see how I would edit it, and how to get a modifiable copy of the Matrix Eater running in the Eclipse IDE.
From that point, honestly to produce it I just click export as Runnable JAR.

**Comment by Frotty** [comment]
> I've used gradle before, but usually just by copying the build scripts because they're annoying syntactically.  

Maybe take 10 minutes to read a 101 guide then? gradle uses groovy. It's simple and useful for many things once you get the hang of it.
I am simply trying to get some definite java libs for wc3 stuff that can be easily built and obtained, without lots of clutter and bad dependencies.
I have done that for jmpq, water's wc3 libs, I've used oger's before to render wc3 in libgdx, and want to continue this some day.
But it's fine, it's probably better for me to fork & cleanup myself once I need it.
Thanks anyways.

Oh an matrix eater is great. Maybe not the best name choice. Ive used it and liked it, but also found 4-5 things i would instantly change on my first use.

**Comment by Retera** [comment]
That is cool. I share your inspiration for making better Wc3 libs even though I agree that my code is crap right now. Do you happen to have the libgdx code you are talking about shared online somewhere? Part of the reason I uploaded my code here is that, for me, knowing how much code was lost over the years in Warcraft 3 modding by people who did not open source, I find it to be more important for me to share my code so people like you can find it, even if it is in a state of disrepair, just in case you can get even one ounce of usefulness out of it. When that happens, that's one small thing you did not have to reinvent yourself.

Yes, the matrix eater is a bad name. Originally I was a kid in high school who liked to use Oinkerwinkle's tools and did not communicate with other WC3 modding hobbyists online, and I just never thought to download Magos's model editor nor MdlVis because I knew the Oinkerwinkle Vertex Modifier & Prophet's Wc3 Viewer combination that I already had pretty well. So, the project started my first summer after having a computer science class in high school, when I sat down and rewrote Oinkerwinkle's Vertex Modifier because the background wasn't working on Win7 and was black instead of white.

When I finish making whatever it is that I am trying to turn this codebase into, if it is good enough and worthy of the name, it is possible that I will rename it to something like War3 Studio Max or Retera's Model Editor. But it is not worthy of such a name in its current state, yet.

**Comment by Retera** [comment]
The repo uses gradle now, and has for about a year, so I am going to close this issue. Please open a new one if you have further concerns.

**Comment by Frotty** [comment]
yay
